### ISSUE TITLE
pod install error

### ISSUE THREAD

**Issue by joreilly** [rickclephas/KMP-NativeCoroutines#1]
Getting following errors when I open project (in AS Arctic Fox).

Executing of 'pod install' failed with code 1.
Error message:
[!] No `Podfile' found in the project directory.

Please, check that file "/Users/joreilly/dev/github/KMP-NativeCoroutines/Podfile" contains following lines in header:
source 'https://cdn.cocoapods.org'

Please, check that each target depended on NativeCoroutinesSampleShared contains following dependencies:

**Comment by rickclephas** [comment]
My bad forgot to update the location of the Podfile in the `build.gradle.kts` when I moved it to the sample folder... just fixed the path 😇 .
