### ISSUE TITLE
How to pause flow collection in swift

### ISSUE THREAD

**Issue by iamanbansal** [rickclephas/KMP-NativeCoroutines#102]
How to pause flow collection when move to another screen? 

Like in Android we have `collectAsStateWithLifecycle()` or `repeaseOnLifeCycle`  which pause collection based on lifecycle events. Below swift code would pause the publisher to emit but not Flow.

```swift
let publisher = createPublisher(for: clock.time)

var subscription: AnyCancellable? 

var body: some View {
  ...
        }
        .onAppear(){
             subscription = publisher.sink { completion in
                        print("Received completion: \(completion)")
                    } receiveValue: { value in
                        print("Received value: \(value)")
                    }
        }
        .onDisappear(){
           subscription?.cancel()
        }
```

**Comment by rickclephas** [comment]
Hi! Cancellations are forwarded to Kotlin, so calling `cancel` should also cancel the `Flow` collection.
However depending on the type of `Flow` the flow itself might not be cancelled.

E.g. the `Clock` example starts a separate job that doesn't care about the number of collectors/subscribers:
https://github.com/rickclephas/KMP-NativeCoroutines/blob/1dd833bb1cc84cdf98ed93a53e92a80e445d9d1c/sample/shared/src/commonMain/kotlin/com/rickclephas/kmp/nativecoroutines/sample/Clock.kt#L13-L28

On the other hand something like the following will cancel the flow:
https://github.com/rickclephas/KMP-NativeCoroutines/blob/1dd833bb1cc84cdf98ed93a53e92a80e445d9d1c/sample/shared/src/commonMain/kotlin/com/rickclephas/kmp/nativecoroutines/sample/tests/FlowIntegrationTests.kt#L13-L20

**Comment by iamanbansal** [comment]
In my case, it's `StateFlow` most of the time. So, is it ok to not cancel the flow or subscriber?
In my above code, on every new subscription, it will create a new collector. So navigating to & fro will lead to opening many unused collectors. Correct me if I'm wrong.

**Comment by rickclephas** [comment]
In that case it's perfectly fine to cancel the subscription.
Creating a subscription will indeed create a new collector. However once the subscription is cancelled so is the collector.

E.g. when using something like the following, you'll notice that the item printing will stop as soon as you cancel the subscription.
```kotlin
val time = _time.onEach { println(it) }
```

**Comment by iamanbansal** [comment]
Awesome! ThankYou!
