### ISSUE TITLE
How can I proof?

### ISSUE THREAD

**Issue by Krakert** [rickclephas/KMP-NativeCoroutines#109]
Not a issues at all, but I have a question.

I am currently graduating and I am doing research on how to better us `KMM`. And on KotlinConf I watched a talk from Salomon Brys and he mentioned `KMP-NativeCoroutines` as the better way for `Coroutines` on iOS, GREAT!!

And now I have an application that uses your `KMP-NativeCoroutines`, but I wanted to know if there is a way to make my research more valid. The application I made works.. But how do I know tasks are not performed on the main Thread?

So I was wondering if you could maybe help me out with a way to prove this, can you `print()` like a ID of a Thread or is there a way to use the debugger to show that the task is running async.

I hope you could help me with this one, would really appreciate the help!

**Comment by rickclephas** [comment]
Hi, that is cool!
You could definitely prove this with a simple check:
```kotlin
println("isMainThread: ${NSThread.isMainThread}")
```
Note: this should be either in your iOS source-set, or you'll need to use expect/actual to access `NSThread.isMainThread`.

KMP-NativeCoroutines uses the `Dispatchers.Default` by default:
https://github.com/rickclephas/KMP-NativeCoroutines/blob/2f1097b3a5c61f358a1a08a8dab332fa689e2ce9/kmp-nativecoroutines-core/src/nativeCoroutinesMain/kotlin/com/rickclephas/kmp/nativecoroutines/CoroutineScope.kt#L10
So `isMainThread` should return `false` unless you explicitly specify a `CoroutineScope` with the `Dispatchers.Main`.

**Comment by Krakert** [comment]
It there a way to proof it in the iOS code? I have cloned your project and added `print(Thread.isMainThread)` 
to the `func loadRandomLetters` but this also prints `true`?

```swift
func loadRandomLetters(throwException: Bool) {
    Task {
        isLoading = true
        result = nil
        do {
            print(Thread.isMainThread)
            let letters = try await asyncFunction(for: randomLettersGenerator.getRandomLetters(throwException: throwException))
            result = .success(letters)
        } catch {
            result = .failure(error)
        }
        isLoading = false
    }
}
```

Before I had a view model that I used in the view that had the `@MainActor` annotation added to it, but this it not really the way to go, and removing the annotation will give me: `Publishing changes from background threads is not allowed;` warnings. I added the same code that you have in your example that has a `protocol` with all the variables that is annotated with `@MainActor`.
On StackOverFLow I found [this post](https://stackoverflow.com/a/73790379/10352461), so Im not sure if it is even possible?

**Comment by rickclephas** [comment]
Yeah indeed. The code from the ViewModel is always run on the main thread due to the `@MainActor` attribute it inherits.
The Kotlin suspend function will by default run in the background. In this case the `asyncFunction(for:)` is the bridge between the two. It will asynchronously await the completion of the suspend function. 
I hope it makes sense 😄.

**Comment by Krakert** [comment]
Dankjewel voor je uitleg 😉! Really helpful information this, really going to help making my research more valid! Ohh and thanks for this amazing work in general! I was able to the coroutines going within a few hours om iOS because of the wonderful work you have done for the KMP and Kotlin community🫶!
