### ISSUE TITLE
Add support for Swift Package Manager

### ISSUE THREAD

**Issue by rickclephas** [rickclephas/KMP-NativeCoroutines#11]

**Comment by ychescale9** [comment]
Hi! Any ETA on this 😃 ?

**Comment by rickclephas** [comment]
No ETA yet.
I am having some issues with SPM/Xcode and my SSH setup. So haven't been using SPM a lot myself.

Created this to see ~~if/~~how many demand there is for SPM support 🙂.

**Comment by ychescale9** [comment]
Thanks! We're using @Lorex7's [fork](https://github.com/Lorex7/KMP-NativeCoroutines) which works but would great to move to official support:)

**Comment by rickclephas** [comment]
[v0.7.0](https://github.com/rickclephas/KMP-NativeCoroutines/releases/tag/v0.7.0) adds support for the Swift Package Manager! The sample has also been updated to use SPM instead of CocoaPods, it's now only using CocoaPods for the shared KMP module.
