### ISSUE TITLE
Cannot find Methods and Properties annotated with @NativeCoroutines in iOS.

### ISSUE THREAD

**Issue by hrodrick** [rickclephas/KMP-NativeCoroutines#112]
We are having an issue since version 1.0 (tried with 1.0.7, 1.0.8 and 1.0.9) where the methods and attributes annotated with `@NativeCoroutines` can not be found on the iOS project.

To verify and test this you can clone the repo from this link https://github.com/rootstrap/FlowForms/tree/feature/binding-fields (branch is feature/binding-fields). Sync with gradle, compile in android, then compile in Xcode.

This is an example case. It happens with the rest of `@NativeCoroutines` methods and fields, like `validateOnValueChange`.
<img width="587" alt="image" src="https://github.com/rickclephas/KMP-NativeCoroutines/assets/26490822/e909d441-1960-4f71-9631-cf7c04b98bab">

Here we are using `statusNative`, based on the [migration guide](https://github.com/rickclephas/KMP-NativeCoroutines/blob/master/MIGRATING_TO_V1.md) it should be used as just `status`, but it isn't recognized neither.
`FFCFlowForm` stands for the `FlowForm` class in a submodule of a KMP library (FlowForms-Core, which is a module within the repository, imported by the shared module).
 
Notes : 

1. The generated FlowFormsNative file is generated like this, where the specific library imports figure as red, but we don't know why or if it really matters. Note that the status field is created as statusNative instead of status 🤔 
<img width="470" alt="image" src="https://github.com/rickclephas/KMP-NativeCoroutines/assets/26490822/1a04e37e-eafe-48b9-90be-3e96132e1b95">

2. This didn't happened before 1.0.0 and the library was working as expected. (but we can't revert to before 1.0 because of a gradle update on our side)

**Comment by rickclephas** [comment]
Your `shared` module has an `implementation` dependency on the `FlowForms-Core` module.
Please try and make this an `api` implementation.

> The generated FlowFormsNative file is generated like this, where the specific library imports figure as red, but we don't know why or if it really matters.

Not a 100% sure, but that might be related to it being a generated file. As long as the project compiles this shouldn't be an issue.

> Note that the status field is created as statusNative instead of status 🤔

That is correct. On the Kotlin side you'll have `status` and `statusNative`.
The `@NativeCoroutines` annotation on `status` makes sure that it's hidden from ObjC, which in turn allows the `@ObjCName` annotation on `statusNative` to instruct the compiler to use `status` as its ObjC/Swift name.

> This didn't happened before 1.0.0 and the library was working as expected.

The major difference between 0.x and 1.0 is that 1.0 is using KSP to generate the `Native` extension properties/functions.
In 0.x the plugin would modify your existing classes which meant the `Native` properties/functions were actually part of your classes.

**Comment by hrodrick** [comment]
Hi! Thanks for the explanation. I tried using api instead of implementation but the result is the same, i've also tried cleaning the cache and built files on both Android Studio and Xcode. Still can not found the methods and props annotated with @NativeCoroutine 😞

**Comment by rickclephas** [comment]
Sorry forgot to mention that once it's an `api` dependency you will need to tell Kotlin to export the dependency to ObjC.
https://kotlinlang.org/docs/multiplatform-build-native-binaries.html#export-dependencies-to-binaries

**Comment by jnelle** [comment]
@rickclephas could you please show an example? I can't reproduce this for my project

**Comment by rickclephas** [comment]
@jnelle I see you are using CocoaPods.
In that case add the exports to the `kotlin.cocoapods.framework` section:
```kotlin
export(project(":dependency"))
```

Also make sure to use `api` instead of `implementation` for your project dependencies that are using KMP-NativeCoroutines.

**Comment by jnelle** [comment]
Thanks for the quick reply!

I changed my build.gradle.kts in shared to the following:

```

plugins {
    kotlin("multiplatform")
    kotlin("native.cocoapods")
    id("com.android.library")
    id("com.rickclephas.kmp.nativecoroutines")
    id("com.google.devtools.ksp")
}

kotlin {
    android {
        compilations.all {
            kotlinOptions {
                jvmTarget = "1.8"
            }
        }
    }
    iosX64()
    iosArm64()
    iosSimulatorArm64()




    cocoapods {
        summary = "Some description for the Shared Module"
        homepage = "Link to the Shared Module homepage"
        version = "1.0"
        ios.deploymentTarget = "14.1"
        podfile = project.file("../iosApp/Podfile")
        framework {
            baseName = "shared"
            isStatic = true
            export("com.rickclephas.kmm:kmm-viewmodel-core:1.0.0-ALPHA-8")
        }

        extraSpecAttributes["resources"] =
            "['src/commonMain/resources/**', 'src/iosMain/resources/**']"
    }

    kotlin.sourceSets.all {
        languageSettings.optIn("kotlin.experimental.ExperimentalObjCName")
    }

    sourceSets {
        val commonMain by getting {
            dependencies {
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.1")
                implementation("io.ktor:ktor-client-core:2.3.0")
                implementation("io.ktor:ktor-client-content-negotiation:2.3.0")
                implementation("io.ktor:ktor-serialization-kotlinx-json:2.3.0")
                implementation("io.ktor:ktor-client-cio:2.3.0")
                implementation("dev.gitlive:firebase-auth:1.8.1")
                implementation("dev.gitlive:firebase-firestore:1.8.1")
                implementation("org.jetbrains.kotlinx:kotlinx-datetime:0.4.0")
                implementation("io.github.aakira:napier:2.6.1")

                implementation(project(":domain"))
                implementation(project(":courses"))
                implementation(project(":auth"))

                api("com.rickclephas.kmm:kmm-viewmodel-core:1.0.0-ALPHA-8")
                api("io.insert-koin:koin-core:3.4.0")

            }
        }
```
But unfortunately I got the following error:

<img width="944" alt="image" src="https://github.com/rickclephas/KMP-NativeCoroutines/assets/36324542/5e3abfe3-afb2-483a-be9e-76ee1e5b1dcb">


with the following stacktrace:

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_SharedKmm_viewmodel_coreKMMViewModel", referenced from:
      objc-class-ref in KMMViewModel.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

**Comment by rickclephas** [comment]
@jnelle alright in that case just applying the KSP plugin should be enough.
You shouldn't need to export KMM-ViewModel.
I guess exporting it changes the name of `Kmm_viewmodel_coreKMMViewModel`.

**Comment by jnelle** [comment]
Thank you very much, this worked for me! :)

**Comment by hrodrick** [comment]
Hi @rickclephas, sorry for the delay to answer. Thank you very much! I was missing that setup. Now it is working for me :).
