### ISSUE TITLE
github workflow iOS build error

### ISSUE THREAD

**Issue by joreilly** [rickclephas/KMP-NativeCoroutines#118]
This could very likely be issue on my side so feel free to close but just in case it's some known issue.  Various apple clients run fine in XCode locally but when doing build using `xcodebuild` in github workflow  I'm getting following

```
error: could not find module 'KMPNativeCoroutinesAsync' for target 'arm64-apple-ios-simulator'; found: x86_64-apple-ios-simulator, at: /Users/runner/Library/Developer/Xcode/DerivedData/PeopleInSpaceSwiftUI-foyviyaqaqulqqflewtrnydiylha/Build/Products/Debug-iphonesimulator/KMPNativeCoroutinesAsync.swiftmodule
import KMPNativeCoroutinesAsync
       ^
```

This is from https://github.com/joreilly/PeopleInSpace/actions/runs/5171093034/jobs/9314419045?pr=226 when building following branch https://github.com/joreilly/PeopleInSpace/tree/kotlin_1_9_beta

XCode project is using SPM version of `KMP-NativeCoroutines` and is using version `1.0.0-ALPHA-10`

The `xcodebuild` command is successful when run locally (on Apple Silicon laptop) so suspect it's related to mac runners being used.

This branch is using Kotlin `1.9.0-Beta` and includes some refactoring of XCode project so that could be a factor.

**Comment by rickclephas** [comment]
Hmm strange, not sure what is going wrong. The sample project is also using SPM and the tests of said sample are executed with `xcodebuild`, maybe you can spot the difference.

P.S. I tried to build this locally for a Rosetta simulator, but that worked as well 😅.

**Comment by joreilly** [comment]
Thanks, I'll take a closer look at that.

**Comment by ilmooo** [comment]
> Thanks, I'll take a closer look at that.

Hi @joreilly, did you find a solution for your problem? I'm having a similar issue when running tests in Bitrise using M1 device, worked before with Intel-based machines.

Error is similar, except it's for Combine-module and the targets are reversed:
`error: could not find module 'KMPNativeCoroutinesCombine' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator,`

**Comment by joreilly** [comment]
Hmm, I actually left `build` from command line when I updated it!  I'll take a look again shortly to see if still an issue or not.
