### ISSUE TITLE
kotlin 1.9.0

### ISSUE THREAD

**Issue by weijunfeng** [rickclephas/KMP-NativeCoroutines#121]
When I upgrade kotlin 1.9.0 version, it has the following error
```
Cannot change attributes of dependency configuration ':xx:podDebugFrameworkIosX64' after it has been resolved
```
this why?

**Comment by rickclephas** [comment]
Hmm interesting, there aren't much Kotlin 1.9.0 related changes in KMP-NativeCoroutines.
Could you possibly provide a reproducer? Or if your project is open-source then that would work as well.

**Comment by weijunfeng** [comment]
Introduced ksp and NativeCoroutines plug-ins in my project, the versions are as follows
```
plugins {
    kotlin("multiplatform")
    id("com.android.library")
    id("com.rickclephas.kmp.nativecoroutines") version "1.0.0-ALPHA-13"
    id("com.google.devtools.ksp") version "1.9.0-1.0.11"
}
```
When there is configuration like below in my build.gradle.kts file, it will build error
```
project.afterEvaluate {
    // is fail
    tasks.forEach {

    }
    // is ok
    tasks.configureEach {

    }
}
```
When I import only one of ksp or NativeCoroutines it is fine, i don't know why

**Comment by rickclephas** [comment]
Thanks for the update. In that case please use `configureEach` instead, it will make sure that the tasks are configured lazily.
The KMP-NativeCoroutines plugin configures the required KSP setup for you, which is probably why you are only seeing the error once both plugins are applied.

**Comment by petin** [comment]
I am facing the same issue since kotlin 1.9.0 version, when I am using this library in combination with:
`id("dev.icerock.mobile.multiplatform-resources")`

If I am using only one of these 2 libraries the gradle sync works. Using both of them fails with:
`Cannot change attributes of dependency configuration ':shared:iosX64CInteropApiElements' after it has been resolved`

**Comment by rickclephas** [comment]
@petin that seems to be a conflict with [moko-resources](https://github.com/icerockdev/moko-resources) which is eagerly resolving the Kotlin targets. This prevents KMP-NativeCoroutines from configuring KSP.
I would recommend subscribing to https://github.com/icerockdev/moko-resources/issues/535.
