### ISSUE TITLE
KMPNativeCoroutinesRxSwift gives error on iOS < 13

### ISSUE THREAD

**Issue by tylerwilson** [rickclephas/KMP-NativeCoroutines#122]
I am importing only the RxSwift version into my project, which has a min iOS of 11.0. According to the README, RxSwift should have a supported version of 9.0. But it fails, since the Package.swift says iOS min is 13.0.

I am o expert in SPM or the Package format, but I wonder if there is a way to adjust the Package.swift to properly set the min of RxSwift target to something lower than 13.0.

**Comment by tylerwilson** [comment]
For now I am bumped my app to iOS 13. But it would be nice if the SPM was set to 9.0 as documented (I only need 11.0 myself).

Note that it might be that using as a Pod might work, but then I have to move everything else I have moved to SPM - RxAlamofire/Alamofire, NSObject+Rx, RxSwift/RxCocoa etc.

**Comment by rickclephas** [comment]
Hi! Yeah as far as I know SPM doesn't currently support target specific platforms.
However that is one of the reasons why I am tagging SPM specific releases.
When you just need RxSwift you can use version `1.0.0-ALPHA-13-spm-rxswift`. That "release" only includes the RxSwift implementation and does support iOS 9.0 and above:
https://github.com/rickclephas/KMP-NativeCoroutines/blob/6749dc2ad3fad92d87dd0ae2ab53fe780d64a7ce/Package.swift#L6

**Comment by tylerwilson** [comment]
Ah, very nice. Sorry I missed that. Just updated it, set my min to 11.0, and runs like a charm.
