### ISSUE TITLE
Compilation error on generated code when using  @ObjCName(swiftName = "_")

### ISSUE THREAD

**Issue by aoriani** [rickclephas/KMP-NativeCoroutines#124]
I used  `@ObjCName(swiftName = "_")` with the goal of not requiring Swift callers to pass the parameter name.  But that seems to create a problem for the code generator. It sets an empty string for the Objective-C name for the parameter

**Input Code** 

```kotlin 
suspend fun fetchString(@ObjCName(swiftName = "_") param: Int): String {
    println("Starting")
    delay(100)
    withContext(Dispatchers.IO) {
        println("in some IO thread")
        delay(1000)
    }
    println("back on original thread")
    return param.toString()
}
```

**Generated Code**

```kotlin 
@OptIn(ExperimentalObjCName::class)
@ObjCName(name = "fetchString")
public fun fetchStringNative(@ObjCName(name = "", swiftName = "_") `param`: Int):
    NativeSuspend<String> = nativeSuspend(null) { fetchString(`param`) }
```

Compiler error
```
Empty @ObjCName names aren't supported
```

**Comment by rickclephas** [comment]
Thanks for the report! This has been fixed in [v1.0.0-ALPHA-14](https://github.com/rickclephas/KMP-NativeCoroutines/releases/tag/v1.0.0-ALPHA-14).
