### ISSUE TITLE
How does one consume a @NativeCoroutinesState?

### ISSUE THREAD

**Issue by chokokatana** [rickclephas/KMP-NativeCoroutines#135]
I've been reading the README up and down but can't figure out how the `@NativeCoroutinesState` is meant to be consumed in swift. I've grepped the repo for `asFlow` and there's no usage example. Grepping for `NativeCoroutinesState` only shows the README lines and compiler/gradle/ksp tests implementations, which don't seem to show how to use this from swift (aka: a `.swift` file using this).

On the kotlin side I have:

```
    private var mTestInt = MutableStateFlow(3)
    @NativeCoroutinesState
    val testInt = mTestInt.asStateFlow()
```

Then, on the `.swift` side I have tried:
```
        let handle = Task {
            do {
                let a = mFoo.testIntFlow()
            } catch {
                print("Failed with error: \(error)")
            }
        }
```
But I have no idea how to autocomplete that or use it, as seen by the following IDE errors. Any help?

<img width="425" alt="Captura de pantalla 2023-08-16 a las 14 03 40" src="https://github.com/rickclephas/KMP-NativeCoroutines/assets/38753915/8f8c638b-e605-4e3b-8f56-08db6ff3cbec">

<img width="913" alt="Captura de pantalla 2023-08-16 a las 14 03 48" src="https://github.com/rickclephas/KMP-NativeCoroutines/assets/38753915/69657c25-9857-4aa9-a2d4-5c7367e8f69c">

<img width="927" alt="Captura de pantalla 2023-08-16 a las 14 04 21" src="https://github.com/rickclephas/KMP-NativeCoroutines/assets/38753915/256e42b0-0e1a-4382-bcc6-0e807abb198a">

**Comment by rickclephas** [comment]
`@NativeCoroutinesState` and `@NativeCoroutines` only defer in the declaration names.
For example the following Kotlin code:
```kotlin
@NativeCoroutinesState
val testInt = mTestInt.asStateFlow()
```

produces a property called `testInt` that returns the current value and a property called `testIntFlow` that returns the native representation of the Flow.

When using the same code with `@NativeCoroutines` you would get a property called `testIntValue` that returns the current value, and the `testInt` property will return the native representation of the Flow.

Regardless of the annotation you can consume the Flow with one of the Swift helper functions.
For Swift Concurrency that would be [`asyncSequence(for:)`](https://github.com/rickclephas/KMP-NativeCoroutines#asyncsequence):
```swift
import KMPNativeCoroutinesAsync

let handle = Task {
    do {
        let sequence = asyncSequence(for: mFoo.testIntFlow)
        for try await value in sequence {
            print("Got value: \(value)")
        }
    } catch {
        print("Failed with error: \(error)")
    }
}
```

**Comment by chokokatana** [comment]
Thanks for the response. In a totally async fashion I kept trying to understand the API and finally got an example:
```
    private var task: Task<(), Never>?

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)

        let task = Task { [weak self] in
            do {
                let seq = asyncSequence(for: mFoo.testIntFlow)
                for try await value in seq {
                    print("Got value '\(value)'")
                }
            } catch {
                print("Failed to get flow \(error)")
            }
            self?.task = nil
        }
    }

    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)

        task?.cancel()
        task = nil
    }

```
