### ISSUE TITLE
KMP-NativeCoroutines in child modules

### ISSUE THREAD

**Issue by smworks** [rickclephas/KMP-NativeCoroutines#136]
I have Kmm module which I use for building xcframework. If I add @NativeCoroutines annotation on any methods or variables in that module, it seems to work as expected and I can access them in xcode project.

But if I setup KMP-NativeCoroutines in any of the child modules of Kmm module, I can see that ksp is generating code where @NativeCoroutines is used, but when exporting framework to iOS, those fields seem to become hidden or maybe not exported at all. If I move code from child module to parent Kmm module, then in xcode those hidden fields appear.

Is this expected behaviour for child modules? Any way to work around this instead of just migrating all code into Kmm module?

**Comment by rickclephas** [comment]
Hi. Yeah, that is kind of expected.
KMP-NativeCoroutines generates extensions, which won't be part of the public API of your xcframework module.

To access those extensions from Swift, you would need to [export](https://kotlinlang.org/docs/multiplatform-build-native-binaries.html#export-dependencies-to-binaries) your child module.
