### ISSUE TITLE
Flow single collect

### ISSUE THREAD

**Issue by elkhoudiry** [rickclephas/KMP-NativeCoroutines#137]
Hello, I'm using version `1.0.0-ALPHA-12` and having a setup like this

Swift

```
handle = Task {
            let flow = viewModel.stream
            do {
                let stream = asyncSequence(for: flow.streamFlow)
                for try await state in stream {
                    print("[LOG] collected something")
                    
                }
            } catch {
                print("[LOG] test Failed with error: \(error)")
            }
        }
        
        func doEvent(event: ...... ) {
        Task {
            await asyncResult(for: viewModel.doEvent(event:  .....))
        }
    }
```

Kotlin

```
    private val state = MutableStateFlow(initState())
    @NativeCoroutinesState
    val stream = state.asStateFlow()

    suspend fun updateLoginState(newState: (LoginState) -> LoginState) {
        state.emit(state.value.copy(loginState = newState(state.value.loginState)))
        println("[LOG] new value: ${state.value}")
    }
```

When i start listening to flow stream on ios i collect only a single value at the beginning and the line `  print("[LOG] collected something")` get called once .
but it's never collecting again any values when emitting new states using the `doEvent` function on ios mean while the line `  println("[LOG] new value: ${state.value}")` getting called every time with new state correctly .
and there are no errors are being thrown in ios collection the flow

what could be the problem here ?

**Comment by rickclephas** [comment]
Thanks for the report! Could you possibly share a reproduction sample?

**Comment by elkhoudiry** [comment]
Hello @rickclephas well while i was working on creating reproduction sample i found out that i was doing something wrong with `koin` and it the problem.
I will close this issue and thanks for your help
