### ISSUE TITLE
Problem to use Flow in Swift

### ISSUE THREAD

**Issue by alexfelipe** [rickclephas/KMP-NativeCoroutines#142]
Hello, I'm starting my studies im KMP and I liked that purpose of this project, but, in my first attempt I've got this problem:

![CleanShot 2023-10-16 at 09 35 21@2x](https://github.com/rickclephas/KMP-NativeCoroutines/assets/8989346/95f2f5b1-58ef-4637-9fd8-e3be6aac05bf)

And I don't have idea the reason... I checkout if the code was generated and was done:

![CleanShot 2023-10-16 at 09 36 50@2x](https://github.com/rickclephas/KMP-NativeCoroutines/assets/8989346/e888376d-e579-4146-abfc-25e9ba72f317)

> I created the `alex` to test if the problem is because the Flow with my own object hehe

I added the swift dependend as the readme indicate: 

![CleanShot 2023-10-16 at 09 38 20@2x](https://github.com/rickclephas/KMP-NativeCoroutines/assets/8989346/8eda042a-8af2-47df-8b79-adb40c07567a)

And I think that I configured the build script as expected: 

```kotlin
import com.rickclephas.kmp.nativecoroutines.gradle.ExposedSeverity.*
import org.jetbrains.kotlin.gradle.ExperimentalKotlinGradlePluginApi

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidLibrary)
    id("com.google.devtools.ksp") version "1.9.10-1.0.13"
    id("com.rickclephas.kmp.nativecoroutines") version "1.0.0-ALPHA-18"
}

@OptIn(ExperimentalKotlinGradlePluginApi::class)
kotlin {

    targetHierarchy.default()
    nativeCoroutines {
        exposedSeverity = ERROR
    }

    androidTarget {
        compilations.all {
            kotlinOptions {
                jvmTarget = "1.8"
            }
        }
    }


    listOf(
        iosX64(),
        iosArm64(),
        iosSimulatorArm64()
    ).forEach {
        it.binaries.framework {
            baseName = "shared"
        }
    }

    sourceSets {
        val commonMain by getting {
            dependencies {
                implementation(libs.kotlinx.datetime)
                implementation(libs.kotlinx.coroutines.core)
                implementation(libs.uuid)
                //put your multiplatform dependencies here
            }
        }
        val commonTest by getting {
            dependencies {
                implementation(libs.kotlin.test)
            }
        }
    }
}

android {
    namespace = "br.com.alura.compras"
    compileSdk = 34
    defaultConfig {
        minSdk = 24
    }
}

kotlin.sourceSets.all {
    languageSettings.optIn("kotlin.experimental.ExperimentalObjCName")
}
```

I tried to do some approaches, but all was unsuccessful... Can you help me? If you need to check my repository: https://github.com/alexfelipe/compras-kmp

Thanks! 😁

**Comment by rickclephas** [comment]
Hi! Your configuration look good. The error you are seeing is because `boughtProducts` is a `Flow` and `asyncFunction(for:)` expects a suspend function.
You can use `asyncSequence(for:)` to convert the `Flow` to an `AsyncSequence`, or `createPublisher(for:)` if you are using Combine.

**Comment by alexfelipe** [comment]
Oh, Ty! Maybe I tought that i've saw a code using the `asyncFunction` or `asyncStream` and I assumed that right approach! Thanks again! ☺️
