### ISSUE TITLE
Stream collect problem: com.apple.root.user-initiated-qos.cooperative

### ISSUE THREAD

**Issue by elkhoudiry** [rickclephas/KMP-NativeCoroutines#145]
I'm facing this crash in production, this stacktrace is from crashlytics on user's device ( iPhone 13 pro ios 16.6.1 ) i can't reproduce locally, after searching a bit ([Url](https://forums.swift.org/t/concurrency-cooperative-queue-crash-with-ios-15-16/61145)) it seems to swift concurrency related but i don't understand much, is this problem related to this library or can i catch this error somehow so it doesn't crash the application, thanks.

Little bit context:
kotlin version: 1.8.21
kmp-native-coroutines: 1.0.0-ALPHA-9
method in line index 10 structure:
```
// Kotlin
object OrderDetailsDomainWrapper {
    @NativeCoroutines
    fun screenStateStream(): Flow<ScreenState> {
        return stream
    }
}
```

```
Crashed: com.apple.root.user-initiated-qos.cooperative
0  libsystem_kernel.dylib         0x7578 __pthread_kill + 8
1  libsystem_pthread.dylib        0x7118 pthread_kill + 268
2  libsystem_c.dylib              0x1d178 abort + 180
3  FeatureInjection               0x438958 konan::abort() + 10
4  FeatureInjection               0x43eee8 (anonymous namespace)::terminateWithUnhandledException(ObjHeader*)::$_1::operator()() const + 34
5  FeatureInjection               0x43ee18 void (anonymous namespace)::$_0::operator()<(anonymous namespace)::terminateWithUnhandledException(ObjHeader*)::$_1>((anonymous namespace)::terminateWithUnhandledException(ObjHeader*)::$_1) + 60
6  FeatureInjection               0x43ec7c (anonymous namespace)::terminateWithUnhandledException(ObjHeader*) + 10
7  FeatureInjection               0x43ec5c (anonymous namespace)::processUnhandledException(ObjHeader*) + 516
8  FeatureInjection               0x43fc38 kotlin::ProcessUnhandledException(ObjHeader*) + 96
9  FeatureInjection               0x441604 Kotlin_ObjCExport_trapOnUndeclaredException + 36
10 FeatureInjection               0x341e10 objc2kotlin_kfun:feature.injection.modules.orderdetails#screenStateStreamNative__at__feature.injection.modules.orderdetails.OrderDetailsDomainWrapper(){}kotlin.Function3<kotlin.Function3<domain.orderdetails.models.ScreenState,kotlin.Function0<kotlin.Unit>,kotlin.Unit,kotlin.Unit>,kotlin.Function2<platform.Foundation.NSError?,kotlin.Unit,kotlin.Unit>,kotlin.Function2<platform.Foundation.NSError,kotlin.Unit,kotlin.Unit>,kotlin.Function0<kotlin.Unit>> + 568
11 iosapp                      0x7a6e4 closure #1 in OrderDetailsViewModel.collectScreenState() + 18 (OrderDetailsViewModel.swift:18)
12 libswift_Concurrency.dylib     0x41948 swift::runJobInEstablishedExecutorContext(swift::Job*) + 416
13 libswift_Concurrency.dylib     0x42868 swift_job_runImpl(swift::Job*, swift::ExecutorRef) + 72
14 libdispatch.dylib              0x15944 _dispatch_root_queue_drain + 396
15 libdispatch.dylib              0x16158 _dispatch_worker_thread2 + 164
16 libsystem_pthread.dylib        0xda0 _pthread_wqthread + 228
17 libsystem_pthread.dylib        0xb7c start_wqthread + 8
```

**Comment by rickclephas** [comment]
It seems there is some kind of unhandled exception in the Kotlin code (`Kotlin_ObjCExport_trapOnUndeclaredException`), which is unexpected since KMP-NativeCoroutines should forward all exceptions from a Flow to your Swift code.

Line 10 actually refers to the `screenStateStreamNative` extension generated by KMP-NativeCoroutines.
Could you possibly share this exact generated declaration?

Also how are you consuming the `screenStateStream` in `OrderDetailsViewModel.swift:18`?

**Comment by rickclephas** [comment]
Btw you might want to consider adding something like [NSExceptionKt](https://github.com/rickclephas/NSExceptionKt) or [CrashKiOS](https://github.com/touchlab/CrashKiOS) to the project.
These libraries will make sure to log the actual Kotlin exception instead of those unhandled Kotlin exception terminations.

**Comment by elkhoudiry** [comment]
Thanks for response

Here is the generated code 

```
@ObjCName(name = "screenStateStream")
public fun OrderDetailsDomainWrapper.screenStateStreamNative(): NativeFlow<ScreenState> =
    screenStateStream().asNativeFlow(null)

```

and the stream is consumed like this

```
    func collectScreenState() {
        handle = Task {
            let flow = wrapper.screenStateStream() // this is line 18 stated in crash stack trace (OrderDetailsViewModel.swift:18)
            do {
                let seq = asyncSequence(for: flow)
                for try await value in seq {
                    DispatchQueue.main.async {
                        self.screenState = value
                    }
                }
            } catch {  }
            self.handle = nil
        }
    }
```
and it's called onAppear function when the screen view appears.

I will try to implement these 2 libraries for better reports, but can we also identify what's the problem here and how it can be fixed or caught so we release a fix as well

**Comment by rickclephas** [comment]
Is your original code snippet the actual code of the `screenStateStream` function?
I would expect the exception to come from that function, based on line 18 of `OrderDetailsViewModel` I don't think it has anything todo with the Swift code.

**Comment by elkhoudiry** [comment]
Here is the related code with more context 

```
object OrderDetailsDomainWrapper : KoinComponent {
    private fun scope(): Scope {
        return getKoin().getOrCreateScope<OrderDetailsDomainScope>(OrderDetailsDomainScope.getScopeName().value)
    }
    
    @NativeCoroutines
    fun screenStateStream(): Flow<ScreenState> {
        return scope().get<ScreenStateRepository>().stream
    }
}
```

Could it be from Koin ? but it shouldn't be the problem since that code shouldn't throw an exception ?
And if the exception is from inside the stream is should be handled by this library right ?

**Comment by rickclephas** [comment]
> Could it be from Koin ? but it shouldn't be the problem since that code shouldn't throw an exception and it's not repeated during good enough testing period so there is no wrong koin configuration ?

I am not that familiar with Koin, but possibly. Although in that case I would indeed expect this to be reproducible.
What's the implementation of `ScreenStateRepository.stream`?

> And if the exception is from inside the stream is should be handled by this library right ?

Correct all exceptions inside the Flow are [caught](https://github.com/rickclephas/KMP-NativeCoroutines/blob/a1269d3052fcc32d3861eaea32b715d58a46fe32/kmp-nativecoroutines-core/src/nativeCoroutinesMain/kotlin/com/rickclephas/kmp/nativecoroutines/NativeFlow.kt#L48).
However the crash happens on line 18, which indicates that the Flow collection hasn't even started when the crash occurs.

I am afraid there isn't much to go on with the current stacktrace.

**Comment by elkhoudiry** [comment]
The implementation of `ScreenStateRepository.stream` is just a combination of some other flows to construct the screen state, but i don't think it's problematic since it never caused an issue during development and staging testing and even on production, that crash only happened 2 times on a specific device then the application ran normally after that :/ 

I would like to implement a hotfix for it that will solve the issue, but i guess i will need to apply one of these libraries that will provide better stacktrace that will help us debugging later i guess

**Comment by rickclephas** [comment]
Alright in that case I don't see any obvious issue, so yeah the only way to know for sure what is happening is to make sure you get a proper stacktrace for the unhandled Kotlin exceptions.

**Comment by elkhoudiry** [comment]
Hello @rickclephas 
While i'm trying to use either of the better kotlin stacktrace liberaries i face this issue while archiving the file
```
Undefined symbols for architecture arm64:
  "_FIRCLSExceptionRecordNSException", referenced from:
      _kfun:com.rickclephas.kmp.nsexceptionkt.crashlytics.$setCrashlyticsUnhandledExceptionHook$lambda$0$FUNCTION_REFERENCE$0.$<bridge-UNNN>invoke(kotlin.Throwable){}#internal in result.o
  "_OBJC_CLASS_$_FIRCrashlytics", referenced from:
      objc-class-ref in result.o
  "_OBJC_CLASS_$_FIRExceptionModel", referenced from:
      objc-class-ref in result.o
  "_OBJC_CLASS_$_FIRStackFrame", referenced from:
      objc-class-ref in result.o
ld: symbol(s) not found for architecture arm64
```

so make the archiving success i need to add `isStatic=true` to gradle framwork settings but then it is not allowed to be uploaded to AppStore and getting this error
```
ERROR: Asset validation failed (90171) Invalid bundle structure. The "iosApp.app/Frameworks/FeatureInjection.framework/FeatureInjection” binary file is not permitted. Your app cannot contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. For details, visit: https://developer.apple.com/documentation/bundleresources/placing_content_in_a_bundle
```

any pointers here ?

**Comment by rickclephas** [comment]
Are you using the CocoaPods integration? Maybe [this](https://youtrack.jetbrains.com/issue/KT-49005/Uploading-an-iOS-app-build-with-CocoaPods-plugin-to-AppStoreConnect-fails-with-ITMS-90171-Invalid-Bundle-Structure) can help.

**Comment by elkhoudiry** [comment]
Actually i'm not using CocoaPods integration in kotlin side or CocoaPods at all in the project, i'm using SPM

**Comment by rickclephas** [comment]
In that case it sounds like an embedding issue similar to what's described [here](https://youtrack.jetbrains.com/issue/KT-53339/MPP-CocoaPods-The-static-framework-fails-to-install-on-a-real-iOS-device#focus=Comments-27-6360223.0-0) and [here](https://stackoverflow.com/a/66738089).

**Comment by elkhoudiry** [comment]
Thanks for response, i will try to tinker with these workarounds and get back to you

**Comment by elkhoudiry** [comment]
I tried this solution 
```
tasks.named("embedAndSignAppleFrameworkForXcode").configure {
    enabled = false
}
```

without it the app doesn't upload to testflight, and when applying it, the application crashes at launch and i noticed the app size got decreased dramatically

**Comment by rickclephas** [comment]
@elkhoudiry that's interesting, according to [KT-53339](https://youtrack.jetbrains.com/issue/KT-53339) that workaround is the default behaviour for static frameworks since Kotlin 1.8.0. You might want to open a YouTrack issue for that.

**Comment by elkhoudiry** [comment]
Alright @rickclephas thanks for your help, will close this issue now and try to get back when having a more helpful stacktrace
