### ISSUE TITLE
Support Wasm target

### ISSUE THREAD

**Issue by rickclephas** [rickclephas/KMP-NativeCoroutines#146]
Waiting for kotlinx.coroutines support.
Will add support for the Wasm target such that projects with a wasm target will compile.

**Comment by tylerwilson** [comment]
This would be an awesome holiday present. I have some free time and would love to do some wasm experiments. :-)

**Comment by rickclephas** [comment]
FYI [v1.0.0-ALPHA-23-kotlin-2.0.0-Beta2](https://github.com/rickclephas/KMP-NativeCoroutines/releases/tag/v1.0.0-ALPHA-23-kotlin-2.0.0-Beta2) adds support for projects with a `wasmJs` target.

**Comment by tylerwilson** [comment]
Very nice! Just curious, would this be usable with Kotlin 1.9.21 as well? Just curious because it seems like most of the other libraries like Compose only support 1.9.21 and wasmJs is working there too.

**Comment by rickclephas** [comment]
@tylerwilson yeah it will eventually work with Kotlin 1.9.21 as well. Though since this requires kotlinx.coroutines 1.8.0-RC it's only available in the pre-release version. Once we get 1.8.0 I'll merge this to the stable version.

Note: Compose also has pre-release [builds](https://androidx.dev/storage/compose-compiler/repository) with support for EAP Kotlin versions.

**Comment by GuilhE** [comment]
> @tylerwilson yeah it will eventually work with Kotlin 1.9.21 as well. Though since this requires kotlinx.coroutines 1.8.0-RC it's only available in the pre-release version. Once we get 1.8.0 I'll merge this to the stable version.
> 
> Note: Compose also has pre-release [builds](https://androidx.dev/storage/compose-compiler/repository) with support for EAP Kotlin versions.

https://github.com/Kotlin/kotlinx.coroutines/releases/tag/1.8.0
🥳
