### ISSUE TITLE
IllegalStateException: Only Flow properties supported

### ISSUE THREAD

**Issue by estivensh4** [rickclephas/KMP-NativeCoroutines#148]
when generating the compilation I'm getting this error 
i: [ksp] provider(s) loaded: [com.rickclephas.kmp.nativecoroutines.ksp.KmpNativeCoroutinesSymbolProcessorProvider].
e: [ksp] java.lang.IllegalStateException: Only Flow properties supported

kotlin: 1.9.20
ksp: 1.9.20-1.0.14
native-coroutines: 1.0.0-ALPHA-20

**Comment by rickclephas** [comment]
This error indicates that you have annotated a non-Flow property with one of the `@NativeCoroutines` annotations.
Could you possibly share the relevant code?

**Comment by rickclephas** [comment]
This error unfortunately isn't actually very helpful. The inspection provided by the compiler plugin should provide a better error message, but it looks like those are run after KSP. Will take a look at that.
With the [IDE plugin](https://plugins.jetbrains.com/plugin/22481-kmp-nativecoroutines) it should be easier to identify the invalid annotation.

**Comment by estivensh4** [comment]
> This error unfortunately isn't actually very helpful. The inspection provided by the compiler plugin should provide a better error message, but it looks like those are run after KSP. Will take a look at that. With the [IDE plugin](https://plugins.jetbrains.com/plugin/22481-kmp-nativecoroutines) it should be easier to identify the invalid annotation.



> This error indicates that you have annotated a non-Flow property with one of the `@NativeCoroutines` annotations. Could you possibly share the relevant code?

I have an implementation error in the ViewModel with a variable, but I saw that it is not from the library so I proceed to close the issue.
