### ISSUE TITLE
exposedSeverity = ERROR with sqldelight

### ISSUE THREAD

**Issue by vanniktech** [rickclephas/KMP-NativeCoroutines#154]
I like the idea of:

```kotlin
nativeCoroutines {
    exposedSeverity = ExposedSeverity.ERROR
}
```

however when using sqldelight, the plugin also fails on generated code if you use:

```
sqldelight {
  databases {
    create("MyDatabase") {
      generateAsync.set(true)
    }
  }
}
```

<img width="1232" alt="Screenshot 2023-11-21 at 22 27 42" src="https://github.com/rickclephas/KMP-NativeCoroutines/assets/5759366/cef41302-e673-43da-b188-cb4ab24fc0be">

What do you think the right approach would be? Maybe ignore code that's generated?! I can't set the type internal on sqldelight side.

**Comment by rickclephas** [comment]
Yeah I think it makes sense to ignore generated code for the exposed error/warning. However identifying what declarations are generated isn't as straightforward. I mean all code generated by KSP has an actual Kotlin file.
Maybe we need an option to specify what declarations are generated and should therefore be ignored?
In that case you could tell the plugin that `MyDatabase` is generated (or even the whole database package) and that it should ignore exposed coroutines in those declarations.

**Comment by vanniktech** [comment]
Can you get the path? That function from the screenshot above lies underneath the `build/generated` directory, to be precise `build/generated/sqldelight/code/MyDatabase`.

**Comment by rickclephas** [comment]
That should be possible, however I am not sure if it's possible to identify the project root (since that's more of a Gradle config thing). A `*/build/generated/*` match could work, although not 100% accurate.

**Comment by vanniktech** [comment]
I'd also be fine with having an exclusion list that is path based.

**Comment by rickclephas** [comment]
Starting with [v1.0.0-ALPHA-27](https://github.com/rickclephas/KMP-NativeCoroutines/releases/tag/v1.0.0-ALPHA-27) source files inside `build/generated` are ignored.
The exact list of generated source directories can be customised through the `generatedSourceDirs` option.
