### ISSUE TITLE
SPM import issues

### ISSUE THREAD

**Issue by maximilianlemberg** [rickclephas/KMP-NativeCoroutines#155]
When I try to add the library to my xcode project I get an error stating:

`No such module 'KMPNativeCoroutinesAsync'`

I tried to reset my derrived data, cleared the package caches & also tried to restart xcode.

Altough nothing helped. Sometimes I was able to import KMPNativeCoroutinesCore but thats it.

Did anyone else run into this problem? Your help would be highly appreciated! <3

**Comment by rickclephas** [comment]
This might happen when the frameworks aren't added to the "Frameworks, Libraries, and Embedded Content" section of the app target.

<img width="1111" alt="image" src="https://github.com/rickclephas/KMP-NativeCoroutines/assets/7353419/774d9282-245c-4eee-9710-aababdbe7a13">
