### ISSUE TITLE
Are we going to provide Privacy Info included in the SDK?

### ISSUE THREAD

**Issue by parvez-keeptruckin** [rickclephas/KMP-NativeCoroutines#168]
As per the [requirements](https://developer.apple.com/support/third-party-SDK-requirements/) from Apple, does 
- `KMPNativeCoroutinesCore` 
- `KMPNativeCoroutinesRxSwift`
going to include Privacy manifest in a newer release if it needs to be supported?

**Comment by vanniktech** [comment]
I don't think this is required here.

**Comment by rickclephas** [comment]
I will double-check the API and keep an eye on https://github.com/ReactiveX/RxSwift/issues/2567.
But it likely won't be needed.

Regardless of the outcome, KMP-NativeCoroutines doesn't track or upload any data.

**Comment by rickclephas** [comment]
Based on the [documentation](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files) provided by Apple we don't need a privacy manifest for KMP-NativeCoroutines:
> You need to include a privacy manifest file in your third-party SDK if it’s listed in “SDKs that require a privacy manifest and signature,” in [Upcoming third-party SDK requirements](https://developer.apple.com/support/third-party-SDK-requirements/).

KMP-NativeCoroutines isn't listed.
RxSwift is, but I don't believe declaring a dependency on RxSwift is considered "repackaging".

> Otherwise, include a privacy manifest file in your third-party SDK if it uses required reasons API, collects data about the person using apps that include the third-party SDK, enables the app to collect data about people using the app, or contacts tracking domains.

* non of the required reasons APIs are used
* no data about people is collected
* doesn't allow apps to collect data about people
* no (tracking) domains are being contacted
