### ISSUE TITLE
Issue: receiveCompletion or receiveValue not being called in Swift for createFuture

### ISSUE THREAD

**Issue by atonamy** [rickclephas/KMP-NativeCoroutines#174]
Here a simple replication scenario:

Dependencies:

nativecoroutines: 1.0.0-ALPHA-30
ksp: 1.9.24-1.0.20
coroutines: 1.8.1
kotlin: 1.9.24

Kotlin:
```
@NativeCoroutines
suspend fun simpleFunc(): String {
     delay(2000)
     return "is working"
}
```

Swift:
```
let future = createFuture(for: SimpleFuncNativeKt.simpleFunc())
               
// Now use this future as you would any other
let cancellable = future.sink { completion in
    print("Received completion: \(completion)")
} receiveValue: { value in
    print("Received value: \(value)")
}
```

**Issue:**
`receiveCompletion` or `receiveValue` will never get called. It seems the integration is not working as expected.
same applies for `createPublisher` and `Flow`

**Comment by rickclephas** [comment]
Hi! Are you storing the `cancellable` somewhere permanent?
When using Combine it's important to keep a reference to the `cancellable` as publishers are otherwise immediately cancelled.

**Comment by atonamy** [comment]
> Hi! Are you storing the `cancellable` somewhere permanent?
> When using Combine it's important to keep a reference to the `cancellable` as publishers are otherwise immediately cancelled.

Yes you are right! Cancellable should be defined outside of the function scope where`sink` is called for example in class scope. Could be nice to mention it in the example of README file for beginners like me who not much proficient in iOS development and came from Android background.
