### ISSUE TITLE
iOS: produces 'KotlinBase', not the expected contextual result type 'Timeline'

### ISSUE THREAD

**Issue by vanniktech** [rickclephas/KMP-NativeCoroutines#175]
Using Kotlin 2.0.0 & ALPHA30, I have the following function:

```kotlin
@NativeCoroutines fun observeTimeline(locationHistoryFilter: LocationHistoryFilter): Flow<Timeline>
```

`Timeline` is just a data class that gets emitted.

The Kotlin function for ObjC also gets generated correctly:

```kotlin
@ObjCName(name = "observeTimeline")
public
    fun LocationHistoryDatabase.observeTimelineNative(locationHistoryFilter: LocationHistoryFilter):
    NativeFlow<Timeline> = observeTimeline(locationHistoryFilter).asNativeFlow(null) 
```

However when trying to use it on iOS:

```swift
timelineTask = createPublisher(for: locationHistory.database.observeTimeline(locationHistoryFilter: locationHistoryFilter))
            .receive(on: DispatchQueue.main)
            .sink(
                receiveCompletion: { _ in },
                receiveValue: { [weak self] timeline in
                    self?.timeline = timeline
```

The emitted type is different:

> 1. 'timeline' produces 'KotlinBase', not the expected contextual result type 'Timeline'

<img width="567" alt="Screenshot 2024-05-28 at 12 23 15" src="https://github.com/rickclephas/KMP-NativeCoroutines/assets/5759366/39d886f2-7ffa-4648-b66d-9730592987ae">

and therefore it does not compile. Is this enough information. If not, could you tell me how I can help you out, thanks!

**Comment by rickclephas** [comment]
Thanks for reporting, I have a couple questions:
* could you confirm this is also the case for ALPHA-31?
* did the behaviour change with the Kotlin 2.0 update?
* could you share the `Timeline` class?

**Comment by vanniktech** [comment]
Whops, I am using ALPHA-31. I mixed up the versions. When I did use Kotlin 1.9.24 with 1.0.0-ALPHA-30, everything worked. So I upgraded to Kotlin 2.0.0 and 1.0.0-ALPHA31 it broke. I also have the same version set for Kotlin & iOS.

Sure: 

```kotlin
data class Timeline(
  val records: List<Record>,
)
```

and it has a bunch of class methods, but nothing fancy. `Record` is a class from sqldelight:

```kotlin
public data class Record(
  public val checkInId: String,
  public val checkInTime: Instant,
  public val checkInLocalTime: LocalTime?,
  public val checkInLocalDate: LocalDate?,
  public val checkInTimeZone: TimeZone?,
  public val checkInPlace: String,
  public val checkInDescription: String?,
  public val checkInTagId: String?,
  public val checkInTagName: String?,
  public val checkInTagEmoji: String?,
  public val placeId: String,
  public val placeLongitude: Double,
  public val placeLatitude: Double,
  public val placeDisplay: String?,
  public val placeDescription: String?,
  public val placeAdminArea: String?,
  public val placeLocality: String?,
  public val placeAddressString: String?,
  public val placeLink: String?,
  public val placeRating: Int,
  public val placeCountryCode: String?,
  public val tags: String?,
)
```

For some strange reason, this seems to be the only place in my [18 apps](https://apps.apple.com/la/developer/niklas-baudy/id1543597939?see-all=i-phonei-pad-apps).

Does this one help?

<img width="600" alt="Screenshot 2024-05-28 at 17 42 53" src="https://github.com/rickclephas/KMP-NativeCoroutines/assets/5759366/e72de49f-e26c-4b25-b15e-daeca9a0a2ea">

**Comment by rickclephas** [comment]
Thanks! Interestingly the return type of `observeTimeline(locationHistoryFilter:)` looks okay:
```
@escaping (Timeline, @escaping () -> KotlinUnit, KotlinUnit) -> KotlinUnit
```

I tried to reproduce this in the sample project, but it's compiling without issues.
Do you see any differences between your project and this code?: https://github.com/rickclephas/KMP-NativeCoroutines/commit/2c00956f46b9860ea96c66fecd4624333e5fdade

Btw on what line is the initial error showing? I am assuming this one, right?:
```
self?.timeline = timeline
```

**Comment by rickclephas** [comment]
No problem, glad you figured it out 👍🏻
