### ISSUE TITLE
Crash on iOS 15 in release mode

### ISSUE THREAD

**Issue by hosseinaminii** [rickclephas/KMP-NativeCoroutines#196]
Hi, after updating to version 1.0.0-ALPHA-36 the app crashes on iOS 15 in release mode (it works in debug mode).
Below are versions of the other dependencies:

1. Kotlin: 2.0.21
2. KSP: 2.0.21-1.0.25
3. Coroutine: 1.9.0

I cannot log what crashes because it happens only on real devices in release mode but there are some crash reports in firebase that point to an issue in coroutines like this:
kfun:kotlinx.coroutines.internal.LockFreeLinkedListNode#<get-isRemoved>(){}kotlin.Boolean

I guess it is because of the KMP-NativeCoroutines because when I remove it from a screen it works with no issue.

**Comment by rickclephas** [comment]
Hi. Could you possibly share more details about the crash (specifically the stacktrace), or some kind of reproduction code?

**Comment by hosseinaminii** [comment]
I'm so sorry because it seems it's not related to the KMP-NativeCoroutiens library.
I just used a StateFlow without requesting the server, and it works with no issue. But I guess it is related to the networking or something like that. 
The weird thing is that it only happens on real devices in release mode.
I close this issue, thank you for replying.
