### ISSUE TITLE
Specify whether cancellation of suspending functions and flows is supported or not in the README

### ISSUE THREAD

**Issue by LouisCAD** [rickclephas/KMP-NativeCoroutines#2]
Hello, I think it'd be very helpful to answer that question developers will ask themselves upfront.

All the best!

**Comment by rickclephas** [comment]
Thanks! I have added the motivation behind the library and the limitations it solves to the README.

**Comment by LouisCAD** [comment]
Thanks for editing, it looks like your library supports cancellation. I think it'd be great to show two examples of it in action in Swift code: one for a suspend function, one for for a Flow 

Another question that I'd like to see answered in README: Does it only work with Swift 5.5, and therefore limited to iOS 15 devices and Monterey Macs, or is there an API for Swift 5 and current and older devices?
It's not very clear from the snippets to me.

**Comment by rickclephas** [comment]
Good point! Will definitely add some more useful info and samples later. 

In theory the core should work on as low as iOS 9/macOS 10.9 😄. 
Though currently there is no implementation that supports that. 

At the moment the Combine implementation provides support for iOS 13/macOS 10.15 and above.
The Async implementation uses the new Swift 5.5  features and requires iOS 15/macOS 12.

Support for RxSwift could easily be added to support iOS 9. But I don't there will be many apps that need to support such old versions 🙃.

**Comment by LouisCAD** [comment]
What devs will want is supporting iOS 12 or power since the iPhone 6 is still around with it.

**Comment by rickclephas** [comment]
Yeah I guess it depends on the app and its potential users. Personally I wouldn't support anything below iOS 14 anymore 🙈.

**Comment by rickclephas** [comment]
FYI the README has been updated with a lot more info and code snippets 👍🏻.
