### ISSUE TITLE
Error with asyncStream(for: ) for Flow return function

### ISSUE THREAD

**Issue by uwaisalqadri** [rickclephas/KMP-NativeCoroutines#33]
I am currently experimenting KMM with swift's new concurrency feature (async-await) with this library and I always failed using ``asyncStream``, it showed an error like this

**``Cannot convert value of type '(@escaping ([Manga], KotlinUnit) -> KotlinUnit, @escaping (Error?, KotlinUnit) -> KotlinUnit) -> () -> KotlinUnit' to expected argument type '[Manga]' ``**

**BrowseUseCase.kt**
```
override suspend fun getTrendingManga(): Flow<List<Manga>> {
        return flow {
            try {
                val response = repository.getTrendingManga().map()
                emit(response)
            } catch (e: ApiException) {
                throw ApiError(e.errorTitle, e.errorMessage)
            } catch (e: Throwable) {
                throw e
            }
        }
    }
```

**BrowseViewModel.swift**
```
 func fetchTrendingManga() {
    Task {
      trendingManga = .loading
      do {
        let stream = asyncStream(for: browseUseCase.getTrendingMangaNative())
        for try await data in stream {
          trendingManga = .success(data: data)
        }
      } catch {
        trendingManga = .error(error: error)
      }
    }
  }
```
my project repo:
https://github.com/uwaisalqadri/MangaKu

am I doing it wrong? sorry for the interruption and thanks for your attention

**Comment by rickclephas** [comment]
You are seeing this error because `asyncStream(for:)` only accepts a `Flow` and the `getTrendingManga` function is also a suspend function.
You should first use `asyncFunction(for:)` or `asyncResult(for:)` to await the suspend function.

```swift
do {
        let nativeFlow = try await asyncFunction(for: browseUseCase.getTrendingMangaNative())
        let stream = asyncStream(for: nativeFlow)
        for try await data in stream {
          trendingManga = .success(data: data)
        }
      } catch {
        trendingManga = .error(error: error)
      }
```

**Comment by uwaisalqadri** [comment]
nice, thanks!
