### ISSUE TITLE
Ability to use different NativeCoroutineScope on each platform?

### ISSUE THREAD

**Issue by ankushg** [rickclephas/KMP-NativeCoroutines#34]
Related to #17 

It would be really slick if there was a way to provide a different coroutine scope on each platform.

**Comment by ankushg** [comment]
Actually -- maybe this is already possible using dependency injection?

Example using Koin:
```kt
// common
expect val platformModule: Module

val clockModule = module {
  single { Clock(get()) }
}

class Clock internal constructor(
  @NativeCoroutineScope
  internal val coroutineScope: CoroutineScope
) {
  // all the stuff that's already in there
}

```
```kt
// jsMain
actual val platformModule = module {
  factory<CoroutineScope> { GlobalScope} 
}
```

```kt
// iosMain
actual val platformModule = module {
  factory<CoroutineScope> { CoroutineScope(SupervisorJob() + Dispatchers.Default) } 
}
```

**Comment by rickclephas** [comment]
My first thought is that this would add a lot of extra boilerplate if supported by KMP-NativeCoroutines directly while it could easily be setup in the applications itself.

The way this should work is probably different for every application.
I think there are basically two scenarios:
1. you just need a `CoroutineScope` to be able to start your coroutines from the platform code
2. you are already using a custom scope in your class to control cancellation for example

In the first scenario the default scope should be enough for most of the cases (which we should be different on each platform). For the second scenario a DI solution (like you mentioned) is probably preferred anyway.

But even without DI you could leverage the expect/actual functionality to achieve this.

```kotlin
// commonMain
internal expect fun NativeCoroutineScope(
    context: CoroutineContext = EmptyCoroutineContext
): CoroutineScope

object Clock {
    internal val job = SupervisorJob()
    @NativeCoroutineScope
    internal val coroutineScope = NativeCoroutineScope(job)
}
```

```kotlin
// appleMain
internal actual fun NativeCoroutineScope(context: CoroutineContext): CoroutineScope = 
    CoroutineScope(SupervisorJob() + Dispatchers.Default + context)
```

```kotlin
// jsMain
internal actual fun NativeCoroutineScope(context: CoroutineContext): CoroutineScope = 
    CoroutineScope(GlobalScope + context)
```

This would allow you to have a default context for your scopes while for example still being able to use a custom job.

**Comment by rickclephas** [comment]
I think most (if not all) cases could be solved with one of the above mentioned solutions, so I am going to close this for now.
Feel free to leave a comment if you have a case where these solutions aren't sufficient 😄.
