### ISSUE TITLE
Add support for flows in interfaces

### ISSUE THREAD

**Issue by lotdrops** [rickclephas/KMP-NativeCoroutines#47]
I would like to share interfaces of my ViewModels to iOS instead of the actual implementation, but the native properties are not generated for the flows in my interface. Is there something that needs to be setup for this to work?  
And if not, could this be added?

**Comment by rickclephas** [comment]
Hi! I recently fixed some issues with native properties/functions in interfaces (#35).
Besides using v0.11.2 or above, you shouldn't have to do anything special to use interfaces instead of classes.
Do you have an example of some code for which the native properties/functions aren't generated?

**Comment by lotdrops** [comment]
Hi! Thanks for your quick reply. I've uploaded a project here https://github.com/lotdrops/TestKmpCoroutines   

In the shared code I have the ExampleViewModelImpl, which is the actual implementation in module "example". I also have ExampleViewModel in module "kt", which is an interface that has a `val data: Flow<String>`. This is the flow for which I would like to get a `dataNative`.  
On the iOS side I have the ExampleVMiOS which tries to obtain the `dataNative` but it cannot find it. Before I added the interface, I was using the actual implementation and the `dataNative` was correctly generated. It was when I added the interface that it was no longer available.   

I use the latest version of the library: `const val kmpNativeCoroutines = "0.11.3-new-mm"`.

**Comment by rickclephas** [comment]
Ah alright, then you should also apply the plugin to your "kt" module.

The compiler plugin generates the native properties/functions during the compilation of your Kotlin code.
During compilation it will modify your existing classes/interfaces and add these native declarations.
This is however only possible in the module that contains those classes/interface.

**Comment by lotdrops** [comment]
It was this, I'm sorry 🤦‍♂️🤦‍♂️🤦‍♂️thank you!!
