### ISSUE TITLE
Mutability Issue on suspend function issue with latest Ktor (2.0.0) + RxSwift wrapper

### ISSUE THREAD

**Issue by bopbi** [rickclephas/KMP-NativeCoroutines#59]
When i try to grab a response string using Ktor 2.0.0 `bodyAsText` it show this error

the suspend function looks like this 

```
class Greeting {
    private val client = HttpClient()
    suspend fun getHtml(): String {
        val response = client.get("https://ktor.io/docs")
        return response.bodyAsText()
    }
}
```

and the error

```
Domain=KotlinException Code=0 "Trying to access top level value not marked as @ThreadLocal or @SharedImmutable from non-main thread" UserInfo={KotlinException=kotlin.native.IncorrectDereferenceException: Trying to access top level value not marked as @ThreadLocal or @SharedImmutable from non-main thread, NSLocalizedDescription=Trying to access top level value not marked as @ThreadLocal or @SharedImmutable from non-main thread}
```

**Comment by rickclephas** [comment]
Hi thanks for the report!
Ktor 2.0 actually [dropped support](https://github.com/ktorio/ktor/pull/2739) for the old memory model.
Please try and use the `-new-mm` version with the [new memory model](https://github.com/JetBrains/kotlin/blob/master/kotlin-native/NEW_MM.md).

**Comment by bopbi** [comment]
thanks for help, now i am able to run it after add the `-new-mm` on the library version and add `kotlin.native.binary.memoryModel=experimental` on the `gradle.properties`

i will close the issue
