### ISSUE TITLE
Generating code for transitive dependency

### ISSUE THREAD

**Issue by ychescale9** [rickclephas/KMP-NativeCoroutines#6]
Thanks for the great library!

I was playing with the Compiler plugin and realized it won't generate the `NativeFlow` and `nativeSuspend` for `Flow` or `suspend fun` that come from a transitive dependency / 3rd party library.

A third party library has the following class:
```kt
abstract Store<S : Any> {
  val state: Flow<S> = ...
}
```

I extend this abstract class from my KMP module:
```kt
class MyStore : Store<State> {
  ...
}
```

With this the `nativecoroutines` plugin won't generate `myStore.stateNative`.

I wonder if the compiler plugin can also generate code for the APIs exposed by the module?

**Comment by rickclephas** [comment]
Correct me if I am wrong, but to my knowledge this isn't possible.
Included dependencies are already compiled so compiler plugins (like this one) won't be invoked for the dependencies but only for your own code.

Though in cases where the compiler plugin can't generate the native properties/functions, you could still create them manually via extension properties/functions. See the [Kotlin usage](https://github.com/rickclephas/KMP-NativeCoroutines/blob/d9d495365c7db60ebc5644b9815d4015be74ae96/README.md#kotlin-1) in the README for the code that the plugin generates.
This is exactly how the sample worked before the compiler plugin was added:
https://github.com/rickclephas/KMP-NativeCoroutines/blob/73f741248ac0ff61cd01aca5204efc5a5ed49e7e/sample/shared/src/appleMain/kotlin/com/rickclephas/kmp/nativecoroutines/sample/ClockApple.kt#L1-L9

**Comment by ychescale9** [comment]
My current workaround is to introduce a wrapper interface with it's own `state: Flow<State>` property so the compiler plugin can generate code for these:

```kt
interface Presenter<State: Any, Action: Any> {
  val state: Flow<State>
  suspend fun dispatch(action: Action)
}
```

It's a little bit more boilerplate but it's worth it as we can leverage the codegen:)

> Included dependencies are already compiled so compiler plugins (like this one) won't be invoked for the dependencies but only for your own code.

Yeah that's also my impression. I'll play with it a bit as it should be easy to at least know if this is possible.

**Comment by rickclephas** [comment]
Nice! I guess that's exactly what most projects will do. Especially in larger projects with more logic there will be less cases where you just need a property from a dependency without modification.

P.S. I am no compiler plugin expert so would love to hear if someone knows a way to generate the code for dependencies 😇.
