### ISSUE TITLE
Main fingersecurity

### ISSUE THREAD

**Issue by killgapwalker** [rickclephas/KMP-NativeCoroutines#68]
Imposible hacking...
How to change security level for keyboard ?
Im trying to reach selinux book but otherwise im cant secure keyboard thats giving me big difficulties with accounts?

**Comment by rickclephas** [comment]
@killgapwalker I am not really following, but this doesn't seem to relate to KMP-NativeCoroutines at all.
Please just send an email to support@fingersecurity.app.
