### ISSUE TITLE
Support Kotlin 1.7.20-Beta

### ISSUE THREAD

**Issue by uluckas** [rickclephas/KMP-NativeCoroutines#70]
Hi Rick,
would it be possible to support Kotlin 1.7.20-Beta? 
Would be great help in getting ready for 1.7.20 which has an improvement on [Calling Kotlin suspending functions from Swift/Objective-C](https://kotlinlang.org/docs/whatsnew-eap.html#the-new-kotlin-native-memory-manager-is-enabled-by-default)﻿ (`kotlin.native.binary.objcExportSuspendFunctionLaunchThreadRestriction=none`)

Thanks for your work
Uli

**Comment by rickclephas** [comment]
Version `0.12.6-kotlin-1.7.20-Beta` supports Kotlin 1.7.20-Beta.
You can use that version instead of the `0.12.6-new-mm` one in your Kotlin code (on the Swift side just keep using `0.12.6`).

P.S. when you are using KMP-NativeCoroutines there aren't any restrictions on the calling thread.

**Comment by uluckas** [comment]
Cool. Thanks
