### ISSUE TITLE
Use Method from a lazily initialised class in `asyncStream`

### ISSUE THREAD

**Issue by JonasHiltl** [rickclephas/KMP-NativeCoroutines#79]
Hi,
first of all amazing library and thanks for creating and maintaining ist.

I'm injecting a shared class instance through Koin in SwiftUI. That class has a `MutabelStateFlow` which I want to collect in Swift, preferably through async/await.
But since the injected class is lazy it get the compiler error `Cannot use mutating getter on immutable value: 'self' is immutable`.
Do you know if it's somehow possible to use a lazily initialised variable for the `asyncStream` function. Maybe you already encountered this problem?

```swift
struct ToastView: View {
    @LazyKoin private var queue: ToastQueue

    @State var toast: shared.Toast? = nil
    
    var body: some View {
        VStack {
            ...
        }
        .task {
            do {
                let stream = asyncStream(for: queue.currentToastNative)
                for try await toast in stream {
                    self.toast = toast
                    print("Got toast : \(toast)")
                }
            } catch {
                print("Failed with error: \(error)")
            }
        }
    } 
```

**Comment by rickclephas** [comment]
Hi @JonasHiltl. This seems more like an issue with the `@LazyKoin` property wrapper, `asyncStream` itself shouldn't have any issues with lazy properties.
I couldn't find any documentation about the `@LazyKoin` property wrapper, why exactly is it lazy?
