### ISSUE TITLE
Compilation fails with NoSuchElementException for functions with generic parameters

### ISSUE THREAD

**Issue by liauli** [rickclephas/KMP-NativeCoroutines#8]
Hello 👋🏻 I got this error and it only happens when I try to run any test. here's the message:

```
e: Compilation failed: Sequence contains no element matching the predicate.
 * Source files: *all files in commonTest are mentioned here*
 * Compiler version info: Konan: 1.5.20 / Kotlin: 1.5.20
 * Output kind: LIBRARY
e: java.util.NoSuchElementException: Sequence contains no element matching the predicate.
	at com.rickclephas.kmp.nativecoroutines.compiler.KmpNativeCoroutinesIrTransformer.visitFunctionNew(KmpNativeCoroutinesIrTransformer.kt:232)
	at org.jetbrains.kotlin.backend.common.IrElementTransformerVoidWithContext.visitFunction(IrElementTransformerVoidWithContext.kt:68)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitSimpleFunction(IrElementTransformerVoid.kt:72)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitSimpleFunction(IrElementTransformerVoid.kt:73)

```

After some debugging, I finally found the one that triggers it: [this file from Apollo GraphQL](https://github.com/apollographql/apollo-android/blob/f72c3afd17655591aca90a6a118dbb7be9c50920/apollo-runtime-kotlin/src/commonTest/kotlin/com/apollographql/apollo/mock/TestLoggerExecutor.kt). I added it manually to my `commonTest` in my project. 

Based on the error message, is it because `single` in `visitFunctionNew` can't find any matching function? but if that's true, I'm not sure why it doesn't match. 

```
val originalFunction = declaration.parentAsClass.functions.single {
            it.name == originalName && it.isCoroutinesFunction && it.valueParameters.areSameAs(declaration.valueParameters)
        }
```

**Comment by rickclephas** [comment]
Hi! Looking at the GraphQL function I am guessing it's because of the generic function parameter. 
The generic parameter `D` of the original function will be of a different "type" than the generic parameter `D` of the generated native function.

Will have to take a look at this later, it should be possible to compare the generic types based on it's constraints. 
Though I am not sure if that is needed since generic functions aren't supported in ObjC. 
If these kinds of functions aren't even part of the ObjC framework then we could just skip them completely 🙂.

**Comment by rickclephas** [comment]
Alright can confirm this issue is caused by the generic parameters. Though these kind of functions are part of the ObjC framework (the generics are replaces by the upper bound types) so we can't just skip them.
Will take a look at how to correctly compare the generic types 🙂.

**Comment by liauli** [comment]
Thank you for checking this!

I just realized I also have another [class from GraphQL](https://github.com/apollographql/apollo-android/blob/f72c3afd17655591aca90a6a118dbb7be9c50920/apollo-runtime-kotlin/src/commonTest/kotlin/com/apollographql/apollo/mock/MockNetworkTransport.kt) that's using generic type `D` but I still can build the project with this class in my commontest. At a glance the function on both files are similar, one of the differences is that the other class is an `internal class`. I tried to add internal to the other class and this solved my problem 😃 I'm guessing the native function will not be generated if it's an `internal`?

**Comment by rickclephas** [comment]
>  I tried to add internal to the other class and this solved my problem 😃 I'm guessing the native function will not be generated if it's an internal?

Yeah that is correct the native functions and properties are only generated for public declarations.

**Comment by rickclephas** [comment]
[v0.5.0](https://github.com/rickclephas/KMP-NativeCoroutines/releases/tag/v0.5.0) adds support for generic functions to the compiler plugin. 

I have also added the `NativeCoroutinesIgnore` annotation so that specific functions (or properties) can be ignored/excluded.
Which can be useful in cases where the compiler plugin has trouble with a specific function or property 🙂.

**Comment by andybdahl** [comment]
@rickclephas I am experiencing this generics issue while on `0.11.2`

I have a function that accepts generics, and have narrowed the failure down to exactly that, compilation fails with the error referenced in this issue if I include the function.

Below is the kotlin code that fails, hope you have some idea as to what causes the error and if and how I can fix it while still having the function available to iOS developers.

```kotlin
class UseCaseUtils {

    /**
     * Creates a [Flow] wrapper which will emit values of [Entity] with a delay of the return value of the [extractTimeMillis] block.
     *
     * @param Entity the type of Entity the UseCase returns.
     * @param useCase the use case to wrap.
     * @param extractTimeMillis a block which extracts (or plain returns) a number of milliseconds until the next fetch.
     * @return returns the wrapped [Flow].
     */
    fun <Entity : IEntity> createFlowableUseCase(useCase: suspend () -> Entity, extractTimeMillis: (Entity) -> Long): Flow<Entity> = flow<Entity> {
        while (true) {
            // Invoke usecase to get entity.
            val entity = useCase()

            // Emit entity to flow.
            emit(entity)

            // Delay until next flow using the extractor block.
            delay(extractTimeMillis(entity))
        }
    }

}
```

Compilation fails with the error:
```ruby
java.util.NoSuchElementException: Sequence contains no element matching the predicate.
	at com.rickclephas.kmp.nativecoroutines.compiler.KmpNativeCoroutinesIrTransformer.visitFunctionNew(KmpNativeCoroutinesIrTransformer.kt:227)
```

**Comment by rickclephas** [comment]
Hi @andybdahl thanks for the report! 
I did some quick investigating and created two separate issues for the mentioned build failures. 

As temporary workaround you could manually create the native function:
```kotlin
// commonMain
import com.rickclephas.kmp.nativecoroutines.NativeCoroutinesIgnore

class UseCaseUtils {
    @NativeCoroutinesIgnore
    fun <Entity : IEntity> createFlowableUseCase(
        useCase: suspend () -> Entity,
        extractTimeMillis: (Entity) -> Long
    ): Flow<Entity> { /* ... */ }
}

// iosMain
import com.rickclephas.kmp.nativecoroutines.NativeFlow
import com.rickclephas.kmp.nativecoroutines.asNativeFlow

fun <Entity : IEntity> UseCaseUtils.createFlowableUseCaseNative(
    useCase: suspend () -> Entity,
    extractTimeMillis: (Entity) -> Long
): NativeFlow<Entity> = createFlowableUseCase(useCase, extractTimeMillis).asNativeFlow()
```
