### ISSUE TITLE
Exceptions in Kotlin seem to be completing successfully in Swift

### ISSUE THREAD

**Issue by Philio** [rickclephas/KMP-NativeCoroutines#85]
I ran into a bit of a strange issue.

I have this method in my shared module, that doesn't return anything because there is no useful data to return and throws an exception in the event of an error (in Android I'm just using the server error code to determine what went wrong):

    @Throws(Exception::class)
    suspend fun verifyPhoneNumber(country: String, number: String) =
        verifyRepository.verifyPhoneNumber(country, number)

When I call this from Swift, it always returns `.success` regardless of if an exception was thrown.

I'm running from Swift:

    let result = await asyncResult(for: verifyNumber.verifyPhoneNumberNative(country: country, number: number))
    print(result)

And the logs from the simulator from Ktor/last line from the print statement:

    HttpClient: RESPONSE: 429 Too Many Requests
    METHOD: HttpMethod(value=POST)
    FROM: https://****
    COMMON HEADERS
    -> Content-Length: 48
    -> Content-Type: application/json
    -> Date: Mon, 26 Dec 2022 10:19:54 GMT
    -> Strict-Transport-Security: max-age=15724800; includeSubDomains
    BODY Content-Type: application/json
    BODY START
    {"status_code":429,"error":"Too Many Requests"}
    BODY END
    success(kotlin.Unit)

Could this be a bug, or is it an implementation issue?
I appreciate I can refactor the shared module code to produce a useful result other than `Unit` and that'll solve the problem, but thought it might be worth raising it incase I hit a bug.
Also my first time building an iOS app so likely I'm doing something wrong 😄

**Comment by rickclephas** [comment]
Hey @Philio thanks for raising this issue, exceptions indeed shouldn't result in a success result.
What version of KMP-NativeCoroutines are you using? And could you possibly share the implementation of `verifyPhoneNumber`? Specifically the logic that throws the exception?

**Comment by Philio** [comment]
Hi @rickclephas thanks for the quick response.
It turns out it was a configuration issue with Ktor (not throwing exceptions for 4xx errors by default).
I guess I'm still in the Retrofit/OkHttp mindset at the moment.
Sorry for the false report!
