### ISSUE TITLE
Add Apple Silicon targets

### ISSUE THREAD

**Issue by ychescale9** [rickclephas/KMP-NativeCoroutines#9]
It'd be great to add the following targets:

```
iosSimulatorArm64()
macosArm64()
tvosSimulatorArm64()
watchosSimulatorArm64()
```

Looks like we are currently blocked by `kotlinx-datetime`.

**Comment by rickclephas** [comment]
Indeed. I was waiting for `kotlinx-coroutines-core` to add support (which they did earlier today).
`kotlinx-datetime` shouldn't be an issue since it is only used for the sample and not the actual library 🙂.

**Comment by rickclephas** [comment]
[v0.6.0](https://github.com/rickclephas/KMP-NativeCoroutines/releases/tag/v0.6.0) add support for the Apple Silicon targets.
