### ISSUE TITLE
@NativeCoroutinesState does not work for Interfaces

### ISSUE THREAD

**Issue by cgaisl** [rickclephas/KMP-NativeCoroutines#92]
I have the following use case: I want my common ViewModel to implement a ViewModelInterface, so that I can easily replace it with mock data for SwiftUI/Compose previews. My ViewModelInterface looks something like this:

```
interface MyViewModelInterface {
    fun onButtonPressed()

    @NativeCoroutinesState
    val uiState: StateFlow<MyUiState>
}
```

I expected this to turn my uiState from a StateFlow to MyUiState in my Swift code. However, what actually happens is that uiState is not accessible from Swift at all anymore.

I tried to write the code generation from the annotation myself, but the following does not work either:

```
interface MyViewModelInterface {
    fun onButtonPressed()

    @HiddenFromObjC
    val uiState: StateFlow<MyUiState>
}

@ObjCName(swiftName = "uiState")
val MyViewModelInterface.uiStateValue: MyUiState
    get() = uiState.value
```

One thing that worked for me was putting the objc getter inside the Interface itself. This is a bit clunky though because the iOS specific code has to live in the common code, where the interface is defined.

```
interface MyViewModelInterface {
    fun onButtonPressed()

    @HiddenFromObjC
    val uiState: StateFlow<MyUiState>

    @ObjCName(swiftName = "uiState")
    val MyViewModelInterface.uiStateValue: MyUiState
        get() = uiState.value
}
```

Is there a way to get this to work, or is there an alternative way I could achieve my goals?

edit: I got this to work with an expect/actual interface, but it's still a lot of extra code

```
expect interface MyViewModelInterface {
    fun onButtonPressed()
    val uiState: StateFlow<MyUiState>
}

// iOS
actual interface MyViewModelInterface {
    actual fun onButtonPressed()

    @HiddenFromObjC
    actual val uiState: StateFlow<MyUiState>

    @ObjCName(swiftName = "uiState")
    val MyViewModelInterface.uiStateValue: MyUiState
        get() = uiState.value
}

//Android
actual interface MyViewModelInterface {
    actual fun onButtonPressed()
    actual val uiState: StateFlow<MyUiState>
}
```

**Comment by rickclephas** [comment]
Hi! This is an unfortunate issue with the Kotlin Objective-C interop.
Extensions properties/functions are exported to ObjC as top level properties/functions (also see the [docs](https://kotlinlang.org/docs/native-objc-interop.html#extensions-and-category-members)).

In Swift you should see an extra "class" `MyViewModelInterfaceNative` which contains the `uiStateValue` property/function.
To make this a little better you could define an extension property in Swift (that uses the `uiStateValue` from this native "class").
