### ISSUE TITLE
Mutable flows inaccessible in 1.0.0

### ISSUE THREAD

**Issue by litclimbing** [rickclephas/KMP-NativeCoroutines#93]
I'm migrating my code to 1.0.0 alpha 4 and found an annoying issue.

I have an object with a bunch of `MutableStateFlow`s that are read and written from Swift.  When I annotate them with `@NativeCoroutines` this makes the `tryEmit()` function inaccessible from Swift.

This could be solved by making `@NativeCoroutinesState` annotation generate code like 
```
@ObjCName(name = "time")
var Clock.timeValue
    get() = time.value
    set(value) = time.tryEmit(value)

val Clock.timeFlow
    get() = time.asNativeFlow()
```

**Comment by litclimbing** [comment]
It may also be nice to support the `emit` function for use with `MutableSharedFlow`. I don't personally use this in Swift but a native version of that (it's a `suspend` function) could be helpful if `tryEmit` could fail (it won't for `MutableStateFlow`)

**Comment by rickclephas** [comment]
Starting in [v1.0.0-ALPHA-5](https://github.com/rickclephas/KMP-NativeCoroutines/releases/tag/v1.0.0-ALPHA-5) the `Value` property for a `MutableStateFlow` also contains a setter.
