### ISSUE TITLE
Flow not emitting values.

### ISSUE THREAD

**Issue by kalpeshp0310** [rickclephas/KMP-NativeCoroutines#94]
I am sure I am doing something wrong, But I don't know what. Can you please help?

I have a Flow in common code.

```
val items = flow {
    for (i in 0..10) {
      Napier.d("Emitting $i")
      emit(i)
    }
  }
```

And I am using it in Swift code like this.
```
createPublisher(for: viewExpensesModel.itemsNative)
    .sink { completion in
        switch completion {
        case .finished:
            print("Finished")
        case.failure(let error):
            print(error)
        }
    } receiveValue: { value in
        print(value)
    }
```

Log Output:
```
Emitting 0
```

In logs, I can see that `items` flow emitting value `0`, and after that, nothing happens. I do not get a callback in `receiveValue`, nor does the flow emit the next values.

What am I doing wrong?

I am on the `0.13.3` version of the library.

**Comment by rickclephas** [comment]
I think you are not storing the `AnyCancellable` returned by the `sink` function.
Once the cancellable is deallocated the Flow collection is stopped.
Which would explain why it generates a single value that is never received in your Swift code.

Try storing the cancellable in a property, something like [this](https://github.com/rickclephas/KMP-NativeCoroutines/blob/bb6e5ea0504db706ef52577a66861c015daf2265/sample/Combine/ClockCombineViewModel.swift#L30).

**Comment by kalpeshp0310** [comment]
Ahh, I got it. Thanks a lot.
The code works as expected now. 👍
