### ISSUE TITLE
1.0.0-ALPHA-5 value classes cast to Any

### ISSUE THREAD

**Issue by litclimbing** [rickclephas/KMP-NativeCoroutines#96]
I use value classes in my app fairly extensively to deal with physics units. I have a flow that uses the following class.
```
value class Force(val value: Double): Comparable<Force>
```
This is being cast to `Any` when I try to access it from Swift. Typically this gets cast to a `Double` or `KotlinDouble` when I try to access these properties in Swift.

I tried casting the `Any` value to `KotlinDouble` and got the following error.
`Could not cast value of type 'Shared_kobjcc2' (0x133c8f268) to 'SharedDouble' (0x133c8f638).`

No idea where the type `Shared_kobjcc2` came from or how to cast useful data out of it.

It would be great if value classes could just be reduced to their wrapped typed.

**Comment by litclimbing** [comment]
As a workaround I did the following which works.

```
    private val mutableTargetForceFlow = MutableStateFlow(0.newton)

    @NativeCoroutines
    val targetForceFlow = mutableTargetForceFlow.asStateFlow()
    @NativeCoroutines
    val targetForceValueFlow = targetForceFlow.map{it.value} // Work around flow that produces doubles
```

**Comment by rickclephas** [comment]
Hi, sorry for the delay. Just checked this and unfortunately this is an issue ([53082](https://youtrack.jetbrains.com/issue/KT-53082)/[KT-32352](https://youtrack.jetbrains.com/issue/KT-32352)) with Kotlin Native.

KMP-NativeCoroutines turns your coroutine declarations into regular declarations with a function return type.
It seems that function return types is one of the cases where inline classes are exposed as `id`/`Any`.

Please keep an eye on those YouTrack issues.
